name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics generales
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          user: RubenCayuelas
          template: classic
          base: header, activity, community, repositories, metadata
          repositories: 1000
          repositories_forks: yes
 
      - name: Contributions calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RubenCayuelas
          base: ""
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
 
      - name: Issues and pull requests status
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RubenCayuelas
          base: ""
          filename: metrics.plugin.followup.svg
          plugin_followup: yes
          plugin_followup_sections: repositories
